### PR TITLE
Add FieldTrip optical density snirf file

### PR DESCRIPTION
**Pull request by rob-luke**
Adds a file exported from FieldTrip with the data in optical density (OD) form. We currently do not have any OD test snirf files. Nor did we have any test files from FieldTrip. See https://github.com/mne-tools/mne-python/pull/10408

### CODE REVIEW

**Comment by larsoner** [comment]
This appears to be a draft so I won't merge. Let me know when it's ready and I'll merge and cut a release!

**Comment by rob-luke** [comment]
Thanks @larsoner, ready for merge now (tests have been written in associated MNE-Python PR)

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
0.131 released

**Comment by rob-luke** [comment]
Thanks @agramfort

**Pull request merged**
