### PR TITLE
Kit data

### PR DESCRIPTION
**Pull request by christianbrodbeck**
@larsoner for https://github.com/mne-tools/mne-python/pull/4512. This also moves all the other KIT testing data into the testing dataset, then we can remove it from the mne-python repo, I figured that's cleaner.

### CODE REVIEW

**Comment by larsoner** [comment]
I'm not sure we want to move them -- it's nice to have some testing files with the repo in case the testing dataset isn't available. And they're already in the repo history so we don't gain too much by removing them AFAIK. So perhaps we should discuss / do that separately.

@agramfort WDYT?

**Comment by christianbrodbeck** [comment]
Ah ok, in that case I could also add the AS data to the mne-python repo, it's only a 170 KB snippet.

**Comment by larsoner** [comment]
At the same time we've mostly stopped adding files to the repo, so here might be better for that even if it's small. It's a weird policy... I'll let @agramfort decide :)

**Comment by agramfort** [comment]
Yes let's not add more but let's keep what we have. It's in the git tree anyway

Alex

**Comment by christianbrodbeck** [comment]
Yeah makes sense, so this adds just the new snippet.

**Pull request merged**
