### PR TITLE
Add FieldTrip testdata derived from MNE python test fiff files

### PR DESCRIPTION
**Pull request by thht**
This PR adds some test data that was generated with the included script. It reads the supplied fiff files and processes them with FieldTrip and then saves the results. (generated data is already attached).

These files are better than the old generated ones:

1. They include Mags, Grads, EEG, EOG and STI channels.
2. As there is an actual FIFF file to load and process in MNE python, results can be compared more reliably.

### CODE REVIEW

**Comment by larsoner** [comment]
How much extra space does this take? Have you tried to make it as small as reasonably possible?

**Comment by thht** [comment]
this is an extra 41M of data.
my idea was to have FieldTrip data that is as close as possible to the original so I can test whether the data still corresponds after epoching and averaging in fieldtrip vs. doing the same steps in mne.

if you think, this should be reduced, it can certainly be done by excluding some channels, for example. but that would also make the tests less straight forward because everything i do in the fieldtrip data generator script would need to be mimicked in the unittests.

**Comment by larsoner** [comment]
Could you for example crop the data to 2 sec? Or better, make use of the existing TRIUX data when loading and processing in FT:

https://github.com/mne-tools/mne-testing-data/tree/master/SSS/TRIUX

?

**Comment by thht** [comment]
SSS/TRIUX data is not really an option.

1. it does not have EEG sensors
2. FT complains that "Warning: No device to head transform available in fif file", so checking whether that worked in the unittests would not make sense.

i could crop down the raw data.

and i also think, we can get rid of the ~3MB of old data.

**Comment by larsoner** [comment]
Can you use `sample_audvis_trunc_raw.fif` then?

**Comment by larsoner** [comment]
... we actually already have cov, evoked, etc. computed for these so in theory your FT calculations should already match those, and you could try just reading both and comparing them. Not sure if that would be easier or harder than what you were already doing, though.

**Comment by thht** [comment]
yes, i am already using `sample_audvis_trunc_raw.fif`.
i am not trying to add any new fif files here. all i do is reading `sample_audvis_trunc_raw.fif` with FT, epoch and average and save the mat files after those three steps (reading the raw data, epoching, averaging).

in my unittests, i read said `sample_audvis_trunc_raw.fif`, process it with MNE, load the mat files i saved with FT and compare whether they match.

**Comment by larsoner** [comment]
Ahh okay. So maybe we could save a tiny bit if you only process 1 sec of data or something. But it probably becomes less easy to debug and understand. 41 MB is quite a lot to add but seems like it might be worth it here. Let's go for it and we can always later add these channel-picking and/or cropping complications if we need to, and save on bandwidth then.

**Pull request merged**
