### PR TITLE
Testing file for mne-python PR #4787

### PR DESCRIPTION
**Pull request by fraimondo**
It's a manually edited MFF container in which the PSG signals has 1 less sample.

### CODE REVIEW

**Comment by agramfort** [comment]
how big are all these new files?

**Comment by fraimondo** [comment]
3.9 Mb.

**Comment by agramfort** [comment]
great thx !

**Comment by agramfort** [comment]
here is the release:
https://github.com/mne-tools/mne-testing-data/releases/tag/0.42

**Comment by fraimondo** [comment]
Thanks!

**Pull request merged**
