### PR TITLE
BOXY files to test reading digaux and different filetypes

### PR DESCRIPTION
**Pull request by kuziekj**
Hello,
@kylemath and I are adding the ability for our import boxy reader to also read and create annotations for any triggers sent using the ‘digaux’ of the Imagent machine (https://github.com/mne-tools/mne-python/pull/7717). The ‘digaux’ information is typically saved in the raw boxy file, along with the AC, DC, and Phase data.

We wish to add three files to the testing dataset to ensure that triggers from the ‘digaux’ are read properly and are comparable to the p_pod software. All three files are from a single recording, made using an ISS Imagent II system and version 0.84 of the BOXY recording software with the following settings:

image

Each file contains approximately seven seconds of data, with a sample rate of 79.4722 Hz and recorded from one detector and eight sources. The sources and detectors were not connected a participant or anything, so the data itself is relatively meaningless. The total size of all files is approximately 348 KB.

The following triggers were sent, in order, using the GPIO pins of a Raspberry Pi 2 connected to the ‘digaux’ (serial port) of the Imagent hardware: ‘1’, ‘2’, ‘3’, ‘4’, ‘5’. The duration of each trigger (ie. how long the GPIO pins of the Pi were ‘ON’) was 500ms, with a 500ms delay between each trigger. Since the BOXY software records the state of the ‘digaux’ at each sample point, the raw boxy file contains consecutive duplicates of each trigger (ie. trigger ‘1’ is recorded for each sample point until a different trigger is sent, or until the current trigger is turned off).

The two native BOXY files (boxy_digaux_unparsed.txt and boxy_digaux_parsed.txt) are from the same recording, and contain the same data, but the data is organised differently. The BOXY recording software allows the user to save the data as either a parsed .txt file or an unparsed .txt file. For the parsed file, each row is a new sample point and each source/detector combination is a column. For the unparsed file, each row is a source and each group of N rows is a sample point. Each column is a detector. Here are images showing how the data is organised, and where the option to save a parsed or unparsed file is in the BOXY software:

Parsed
 
image
image

Unparsed
 
image

BOXY setting
image

 
The third file (p_pod_digaux_unparsed.mat) contains the DC, AC, Phase, and ‘digaux’ data from the unparsed file, immediately after it is loaded by the p_pod software (version 10.6.3). P_pod uses .evt files (saved by other programs) to get trigger information, but the ‘digaux’ is still read from the raw data file. P_pod is also not designed to read parsed data files, hence why this only contains data from the unparsed file.

We wish to accomplish two things with these three files:

1) Ensure the ‘digaux’ is correctly loaded from the raw boxy files and trigger annotations are correct. Should be comparable between file types (parsed/unparsed) and software (MNE/p_pod).
2) Raw data (DC, AC, Phase) should be correctly loaded from the raw boxy file and be comparable between file types and software.

@larsoner @rob-luke please let me know if you need more information or have any questions.

### CODE REVIEW

**Comment by larsoner** [comment]
Sounds good to me, @rob-luke feel free to merge if you're happy

**Comment by rob-luke** [comment]
Thanks @kuziekj for the clear explanation and taking these extra measurements. This looks like a great testing dataset now. You have with and without triggers, with and without parsing, and two different montages. I have just the following questions.

Are the parsed and unparsed data two different recordings? Or is it the same measurement exported in two different ways?

Can we rename the directories and files to be consistent across your testing sets?
For example with the first dataset you have the paths `boxy_short_recording/boxy_p_pod_files/` and the second data set it is `mne-testing-data/BOXY/boxy_digaux_recording/p_pod/`. 

Following on the previous comment can we keep the internal directory structure the same? So somehow modify the previous dataset to indicate if it was parsed or unparsed. @larsoner is it ok to edit the previously committed dataset? I don't think its used anywhere yet. I think its ok to not have the parsed/unparsed folders as you have the info in the filename, but I will leave it to you.

Was the previous dataset parsed or unparsed?

Can we include the boxy version number in the directory and file naming? As we will probably need to include similar recordings with the same general information if new breaking changes in the file format come out. Could we change the two directory names to something like `boxy_0_84_digaux_recording` and `boxy_0_84_notrigger_recording` or something else that describes what they are?

Cheers

**Comment by larsoner** [comment]
>  @larsoner is it ok to edit the previously committed dataset? I don't think its used anywhere yet

Yes. And even if it were used somewhere, we pin to versions so you can restructure things without breaking MNE `master` or other PRs usually. If two PRs both update the dataset in different, breaking ways then it can become problematic, which is a good reason to merge PRs quickly that modify (rather than just add to) the dataset -- but such conflicts are pretty rare.

**Comment by kuziekj** [comment]
> Are the parsed and unparsed data two different recordings? Or is it the same measurement exported in two different ways?

The parsed and unparsed files are the same recording, just exported differently.

> Can we rename the directories and files to be consistent across your testing sets?

For sure, I can change those. I'll change it so any p_pod data is always in a folder called `boxy_p_pod_files` and the raw boxy data can be in the main folder, either `boxy_short_recording` or `boxy_digaux_recording`.

> Following on the previous comment can we keep the internal directory structure the same? So somehow modify the previous dataset to indicate if it was parsed or unparsed.

Sure, I'll modify the names of the previous dataset to indicate if the data was parsed or unparsed.

> Was the previous dataset parsed or unparsed?

The previous dataset was unparsed. I'll modify the file names to indicate this. I think it would be nice to have a parsed version as well but it's an old recording from a different lab.

> Can we include the boxy version number in the directory and file naming? 
> Could we change the two directory names to something like boxy_0_84_digaux_recording and boxy_0_84_notrigger_recording or something else that describes what they are?

Sure thing. Maybe in the file names I'll just indicate if triggers are present or not since you can't have triggers without digaux, but having digaux doesn't necessarily mean you have triggers....

Thanks for the feedback @rob-luke. I'll get these changes done sometime today.

**Comment by kuziekj** [comment]
Alright, file and folder names should now be more consistent and informative across data sets.

For the filenames, I indicated if triggers are present or not rather than if digaux is present. I imagine we care more about the presence of triggers in the raw data rather than the digaux, but perhaps I'm wrong.

I also indicated which version of p_pod was used to load the raw boxy files.

Please let me know if there is anything else I can do.

**Comment by rob-luke** [comment]
> The parsed and unparsed files are the same recording, just exported differently.

This is very nice, it will allow us to test that you can read both files and get the same result and compare ppod.

> I think it would be nice to have a parsed version as well but it's an old recording from a different lab

Don't worry about that then, we have the parsed and unparsed for this set, so that will allow us to test the reading of both.

> and the raw boxy data can be in the main folder, either boxy_short_recording or boxy_digaux_recording

What does short refer to here, is it the duration of recording time? Aren't both recordings just a few (10ish) seconds? To me this is confusing because I think you are referring to fNIRS short detectors (referring to the distance between source and detector being less than 1cm). Can you use another name to avoid this confusion? Perhaps just simply `boxy_0_40_recording`?

Other than the short naming I think we are good to merge. But I just want to check with @larsoner that it was ok to edit the existing file names, they arent used in any test yet, but I guess its not good practice to be changing these things after merge.

**Comment by larsoner** [comment]
Renaming or even replacing is usually fine actually, see above

https://github.com/mne-tools/mne-testing-data/pull/70#issuecomment-670584881

**Comment by kuziekj** [comment]
> What does short refer to here, is it the duration of recording time? Aren't both recordings just a few (10ish) seconds? To me this is confusing because I think you are referring to fNIRS short detectors (referring to the distance between source and detector being less than 1cm). Can you use another name to avoid this confusion? Perhaps just simply boxy_0_40_recording?

Right, sorry for that. I used 'short' since the boxy_0_40 recording is a shortened version of a much longer recording.

At any rate, I changed the name of this folder to just be `boxy_0_40_recording`.

**Comment by rob-luke** [comment]
Thanks @kuziekj 

> Renaming or even replacing is usually fine actually, see above

Ops sorry I missed this.

**Pull request merged**
