### PR TITLE
Adding Neuromag122-Test-File

### PR DESCRIPTION
**Pull request by marsipu**
This adds a Test-File for Neuromag122-Data

### CODE REVIEW

**Comment by agramfort** [comment]
Can you check that such a file was never added in the past ? I remember fixing things with Dip after my visit in Heidelberg

**Comment by marsipu** [comment]
Hi Alex,
I couldn't find a Neuromag122-specific file in the mne-testing-data, at least not when looking at the file-names (I don't know much my way around the testing-dataset yet).
Eric suggested the addition in #8891 of mne-python. And I also showed Dip the problem (it was based on a faulty .mat-File from Fieldtrip and the combined gradiometers were not recognized by channels._compute_ch_adjacency), who suggested opening an issue.

**Comment by larsoner** [comment]
I see code in `test_topomap.py` but it's hacked together using the `coil_type`. Better to have a real file if possible, it's only ~500 kB so not too bad.

**Comment by larsoner** [comment]
0.117 released with MD5 d8df35b2e625e213769e97e719de205c

**Pull request merged**
