### PR TITLE
Nihon Kohden data

### PR DESCRIPTION
**Pull request by fraimondo**
This is testing data for a Nihon Kohden native reader. Includes an exported EDF.

### CODE REVIEW

**Comment by agramfort** [comment]
how big are all the files you added? you made it as small as possible? if so +1 for MRG. thx @fraimondo

**Comment by fraimondo** [comment]
Its 30 seconds at 100 Hz, a few channels, with an EDF file exported for comparison.
I don't have the system, so I asked for the files and they sent me this short recording. 

Is this ok? 

```
mia ➜  mne-testing-data git:(add_nihonkohden) ✗ du -sh NihonKohden 
1.2M	NihonKohden
```

**Comment by agramfort** [comment]
1.2MB is small. Ok for me. Ready to merge?

**Comment by fraimondo** [comment]
I’m ready for step 4.

**Comment by agramfort** [comment]
step 4?

**Comment by fraimondo** [comment]
"4. Once your PR is merged, ask a maintainer to cut a new release of the testing data, e.g. 0.53."

After I have to do the PR in MNE

**Comment by agramfort** [comment]
done https://github.com/mne-tools/mne-testing-data/releases/tag/0.65

>

**Pull request merged**
