### PR TITLE
added testing data for csd from Dennis

### PR DESCRIPTION
**Pull request by alexrockhill**
This is for the CSD method implemented by Dennis, https://github.com/mne-tools/mne-python/issues/4480, https://github.com/nice-tools/pycsd?files=1, @dengemann @larsoner (this is cropped to reduce bloat)

### CODE REVIEW

**Comment by agramfort** [comment]
@alexrockhill can I ask you to avoid caps in filenames so Preprocessing -> preprocessing ? thx

**Comment by dengemann** [comment]
@alexrockhill great you tackle this! Please make sure to be clear about relicensing from GPL to BSD compatible with kind permission from Jürgen Kaiser's, under the condition that all references and original code are highlighted. See the pycsd repo for that (which still is GPL).

**Comment by alexrockhill** [comment]
@dengemann, I just copied it as you had it in nice-tools: https://github.com/mne-tools/mne-python/pull/6910. If it's not good, please let me know.

**Comment by larsoner** [comment]
I'm assuming that code predates our discussion with the authors. The wording as it is now will not permit inclusion (you cannot have code governed by GPL within a library that claims to be BSD).

**Comment by dengemann** [comment]
It’s important once you add the actual code. JK had allowed us to relicense the code. Which has not yet happened (relicensing).

**Pull request merged**
