### PR TITLE
[MRG] SSS: Add data processed by MaxFilter with fine (1D) calibration

### PR DESCRIPTION
**Pull request by wronk**

### CODE REVIEW

**Comment by wronk** [comment]
@Eric89GXL, fine calibration data added

**Comment by Eric89GXL** [comment]
Where is the `sss_cal_3053.dat` file?

**Comment by wronk** [comment]
@Eric89GXL, ready for review/merge

**Comment by Eric89GXL** [comment]
BTW how big is the FIF file you're adding?

**Comment by Eric89GXL** [comment]
Ahh, 10 MB. Good enough

**Comment by Eric89GXL** [comment]
Thanks @wronk. Please in your PR comment that people will need to update their testing datasets after merging your PR.

**Pull request merged**
