### PR TITLE
Test data for extracting cHPI fits from ctf data

### PR DESCRIPTION
**Pull request by bloyl**
This adds a testing dataset to evaluate mne-python PR #4088
https://github.com/mne-tools/mne-python/pull/4088

### CODE REVIEW

**Comment by Eric89GXL** [comment]
There is a `.bak` file in there, is it necessary?

How much space does this use?

**Comment by Eric89GXL** [comment]
Sorry I thought #22 was a dup

**Comment by bloyl** [comment]
Nope they are different PRs but both have the similar issues.

Here are the sizes
11M	./testdata_ctf_mc.ds
4.0K	./testdata_ctf_mc.pos

There is an existing ds file that has chpi turned on. But there just isn't much/any motion in it.

**Comment by Eric89GXL** [comment]
Okay fair enough. Ready for merge from your end now that the .bak files are gone?

**Comment by bloyl** [comment]
yup tests pass locally on PR #4088 so I'm good.

**Comment by larsoner** [comment]
@bloyl I just noticed we don't have an example of actually doing head movement compensation with this data. Is that because you don't typically do it and just want to monitor locations? See any roadblocks to (me) writing a quick example on how you could do it using these data?

**Comment by bloyl** [comment]
I think it would be great to have a motion compensation example on ctf
data. My current work flows just monitor and exclude segments, but
compensation would be interesting to see.

At the time i was looking at it there was lots of discussion about using
maxfilter on ctf gradiometers. My recollection is that on my data,
maxfilter cleaned it up somewhat but it wasn't clear that it was
necessarily better. So I chose the conservative option inorder to move on.

**Comment by larsoner** [comment]
@bloyl to do this I think we'd need a new set of data, either with a phantom or "human phantom" (high SNR subject). For example if you can get someone to sit for a 7 minute auditory N100 experiment (e.g., with earphones in and tones or noise bursts) where they held their head stationary for 1 minute intervals in each of 7 different positions in the helmet (center, front, back, right, left, up, down), we could do a dipole/multi-dipole fit and see that the fit quality and topomaps improve with movement compensation. Basically we could make a real-life example out of https://mne.tools/0.19/auto_examples/preprocessing/plot_movement_compensation.html

**Pull request merged**
