### PR TITLE
Add NIRStar 15.0 recording

### PR DESCRIPTION
**Pull request by rob-luke**
Add fNIRS measurement from NIRX NIRStar version 15.0

The process was similar to #52 except the triggers were [1, 2, 2] and the following montage was used...

Capture1
Capture2

### CODE REVIEW

**Comment by agramfort** [comment]
good to go?

**Comment by rob-luke** [comment]
Yes this is ready to merge. Thanks

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-testing-data/releases/tag/0.76

**Comment by rob-luke** [comment]
Cheers

**Pull request merged**
