### PR TITLE
Adding hdf5 test files

### PR DESCRIPTION
**Pull request by smgutstein**
I used Matlab to convert these files, so they should be in the same format that files created by eeglab would be in

### CODE REVIEW

**Comment by agramfort** [comment]
@smgutstein how did you make these files?

I suggested to call them

test_foobar_v73.set

as EEGLAB calls the files .set too, no matter if the files are written in v6 or v7.3 (HDF5) format.

**Comment by smgutstein** [comment]
OK - can rename. I made them by opening the originals in matlab and then
saving with the new format - i.e. save('test_foobar_v73.set','-v7.3')

**Comment by larsoner** [comment]
Is that the same thing as loading them in EEGLAB and saving them with EEGLAB?

**Comment by larsoner** [comment]
(I mean equivalent in terms of the output file?)

**Comment by smgutstein** [comment]
I think it should be. I can try testing later on, if I get access to a
machine with a Matlab license.

**Comment by larsoner** [comment]
Okay I'll rename the files and push v0.45

**Comment by larsoner** [comment]
Done

https://github.com/mne-tools/mne-testing-data/releases/tag/0.45

**Comment by smgutstein** [comment]
My direct saving is the equivalent of saving with EEGLAB:

I checked how EEGLAB saves files. It occurs in pop_saveset.m around lines
244-250:

    try
        if strcmpi(g.version, '6') save(fullfile(EEG.filepath,
EEG.filename), '-v6',   '-mat', 'EEG');
        else                               save(fullfile(EEG.filepath,
EEG.filename), '-v7.3', '-mat', 'EEG');
        end;
    catch
        save(fullfile(EEG.filepath, EEG.filename), '-mat', 'EEG');
    end;

This is essentially what I did, only I did not specify the -mat option,
since it is a default. Checking the resulting files directly with Python
shows they have 2 keys - EEG (as expected) and '#refs#', which, I believe,
is used by HDF5.

I would've made the direct comparison, but for some reason my EEGLAB is now
claiming that strcmpi(g.version, '6') == 1, so it's saving things the old
way. I don't know what the g struct is or does, but since I found the place
where saving takes place I think there's enough certainty that no unknown
unknowns are lurking in the EEGLAB code.

**Comment by larsoner** [comment]
Excellent, thanks for checking. You should be good to update your PR to use version 0.45 of the testing data, instructions in [step 5 here](https://github.com/mne-tools/mne-testing-data/blob/master/README.md#add-or-change-files-in-the-repo-for-use-with-mne).

**Comment by smgutstein** [comment]
Well, I suppose the point of unit testing is that it forces you to find
your unknown unknowns.

The main one I've found is that I had assumed the structure of the EEG
variable in the sample record I obtained from one of our EEG expts would be
static. This doesn't seem to be the case. When I look at the differences
between test_raw_h5.set (derived from test_raw.set) and test_raw_hdf5.set
(derived from the local expt and which started me on getting hdf5 files
readable), I find, in part, the following:

1. In test_raw_hdf5.set, chaninfo has 4 fields (nodatchans, nosedir,
plotrad & shrink), in test_raw_h5.set, it has 1 (icachansind).

2. In test_raw_hdf5.set, chanlocs is stored as an HDF5 Group with 12 fileds
(X, Y, Z, labels, radius, ref, sph_phi, sph_radius, sph_theta, theta, type
and urchan) in test_raw_h5.set, it's a dataset without named fields (at
least that I know how to get at).

3. (In the limits of my limited understanding) When HDF5 stores things in a
group, it makes certain each member of the group has roughly the same type.
As a result, string variables are stored in uint16 arrays where each number
is the ascii value of a letter. I hard coded, in hdf_2_dict (a method I
added to eeglab.py), conversions for some fields that I knew had to be
converted. But my list was not complete, nor did it make allowance for the
structure differences between the EEG's stored in test_raw_hdf5.set and
test_raw_h5.set

Is there documentation giving:

1. The allowed/possible sets of fields and sub-fields for the EEG variable
2. A listing of which fields contain string values

**Comment by agramfort** [comment]
well I guess this should be documented on the eeglab wiki

**Comment by smgutstein** [comment]
OK - I feel silly. That makes sense.

On Thu, Mar 1, 2018 at 3:13 AM, Alexandre Gramfort <notifications@github.com

**Comment by smgutstein** [comment]
Just so you know, I now have things so that all 4 set files can be read
after Matlab converts them to hdf5 format. I still have to add tests in
test_eeglab and go through and make certain that I convert all variables
that s/b strings from arrays of ascii values when necessary.

**Comment by agramfort** [comment]
thanks for the update. Tell us when we can test.

**Pull request merged**
