### PR TITLE
Add a raw file with an invalid birthday

### PR DESCRIPTION
**Pull request by hoechenberger**
Created with MNE 0.19 via:

```python
import pathlib
import mne

data_path = pathlib.Path(mne.datasets.testing.data_path(download=False))
infile = data_path / 'MEG' / 'sample' / 'sample_audvis_trunc_raw.fif'
outfile = pathlib.Path('/tmp/sample_invalid_birthday_raw.fif')

raw = mne.io.read_raw_fif(infile, preload=True)
raw.pick('EEG 001')
raw.crop(tmin=0, tmax=0.1)

raw.info['subject_info'] = dict(birthday=(5874777, 10, 17))
raw.save(outfile, overwrite=True)
```

Required for https://github.com/mne-tools/mne-python/issues/7492, https://github.com/mne-tools/mne-python/pull/7494

### CODE REVIEW

**Comment by hoechenberger** [comment]
I think I'll just put this in into `mne/io/tests/data/` instead.

**Comment by agramfort** [comment]
please don't put this in the repo it's already too big and creates issues for releases

**Comment by agramfort** [comment]
use the mne-testing-data here.

**Comment by hoechenberger** [comment]
Ok, reopened, feel free to merge if it looks good to you

**Comment by agramfort** [comment]
release done https://github.com/mne-tools/mne-testing-data/releases/tag/0.82

>

**Pull request merged**
