### PR TITLE
Raw EGI MFF files with multiple epochs

### PR DESCRIPTION
**Pull request by rhancockn**
Sample raw MFF files with multiple epochs. For  mne-tools/mne-python#5373 and mne-tools/mne-python#4826.

### CODE REVIEW

**Comment by larsoner** [comment]
How large are these files? Are they as small as possible to demonstrate/test the issue?

Here are two other datasets people posted for testing (from [here](https://github.com/mne-tools/mne-python/pull/4826#issuecomment-378853152) and [here](https://github.com/mne-tools/mne-python/pull/4826#issuecomment-379082054)):

[mff with pause.zip](https://github.com/mne-tools/mne-testing-data/files/2242488/mff.with.pause.zip)
[test_pause_EGI.zip](https://github.com/mne-tools/mne-testing-data/files/2242489/test_pause_EGI.zip)


They are each < 200 kB compressed. If they are smaller than yours and demonstrate the same issue, perhaps we should use them instead? If not, maybe we should add all 3 for completeness? WDYT?

**Comment by larsoner** [comment]
(note: if you do switch to these, please uncompress them before adding them -- `git` will take care of properly compressing the commit)

**Comment by mmagnuski** [comment]
@larsoner The bin file here is 3.82 MB according to github so I think it may be acceptable. As far as I remember the files you link to contain pauses but not events so they are not sufficient to demonstrate the misalignment bug. At least that should be the case for the file I posted, but the other file was linked via wetransfer that has expired.

**Comment by larsoner** [comment]
@mmagnuski where is the file you posted that has events? That plus the file here might be good enough for debugging

**Comment by mmagnuski** [comment]
I'll take a look, I don't remember very well which file it was, and correspondingly where it is now. But I have some big files that due to the problems with events in mff files with puases do not have erps :) Correct realignment of the events brings the erps back.

**Comment by rhancockn** [comment]
The sample file I provided does include ECI events along with the
pause—maybe that's enough?

**Comment by larsoner** [comment]
This does indeed have events, let's get it in -- thanks @rhancockn

**Pull request merged**
