### PR TITLE
MRG: cHPI test data with five chpi coils and head movement corrections by MF

### PR DESCRIPTION
**Pull request by bmaess**
Suggest to add four files: chpi5_raw.fif plus the output of a maxfilter movement correction with the configuration parameters: -frame head -in 8 -out 3 -ctc /neuro/databases/ctc/ct_sparse.fif -cal /neuro/databases/sss/sss_cal.dat -movecomp inter -hpistep 1000 -hpiwin 1000 -hpicons -linefreq 50 -force

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

I'll let @Eric89GXL merge if he's ok

**Comment by Eric89GXL** [comment]
25 MB is a lot to add, but it's probably worth it here. However, can we remove `chpi5_raw_mc.fif`? I don't think we need it for head pos estimation testing since we have the .pos file. In principle we could use it to check movement compensation, but it's probably not worth the increased size right now.

**Comment by Eric89GXL** [comment]
... also could you please add your site's `ct_sparse.fif` and `sss_cal.dat` as e.g. `ct_sparse_Leipzig.fif` (or some other suitable naming scheme)? If we eventually want to do more testing it will help because others can process the files properly.

**Comment by Eric89GXL** [comment]
I made selected changes, pushed to `master`, and cut a test data release

**Comment by bmaess** [comment]
I am going to add the files for the fine tuning and the cross talk suppression by tomorrow. I had added the maxfilter result fif as well, because it had the funny steps in it, which I hope to get rid off with an improved version of maxwell_filter. But it is true, that this file won't be of any use for the mne-python test-suite.

**Comment by Eric89GXL** [comment]
Sounds good. But let's add the fine cal and cross-talk in a separate PR

**Pull request closed without merging**
