### PR TITLE
Eximia testing files.

### PR DESCRIPTION
**Pull request by fraimondo**
10 seconds of RS using an eximia system and the corresponding header and data when read using fieldtrip.

Needed for https://github.com/mne-tools/mne-python/pull/5043

### CODE REVIEW

**Comment by agramfort** [comment]
and new release done: https://github.com/mne-tools/mne-testing-data/releases

thx @fraimondo

**Comment by fraimondo** [comment]
I increased the version.txt file to .43, but the release tag is at .46. Also, MNE-Python currently uses .43. Should I update to .46 in `mne/datasets/utils.py`?

**Comment by agramfort** [comment]
should be fixed now

**Comment by fraimondo** [comment]
Thanks!

**Pull request merged**
