### PR TITLE
[ADD] example motion data in BIDS format for work on implementing motion data in MNE 

### PR DESCRIPTION
**Pull request by JuliusWelzel**
Hi, this is the BIDS formatted motion data to work on https://github.com/mne-tools/mne-python/pull/12141#issuecomment-1795355577. I have drafted a 'RawMotion' reader.

Additionally, I have EEG and EMG data (in BIDS) from this same subject to create meaningful examples.

### CODE REVIEW

**Comment by agramfort** [comment]
42 MB for a .tsv file is huge. Is another file format supported? It would be much smaller is binary format.

**Comment by JuliusWelzel** [comment]
Hi, currently [Motion BIDS only supports `.tsv` format](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/motion.html#motion-recording-data), which will be expanded in the future in line with BIDS.
For the example, I removed the `.tsv` file and added a parquet using snappy compression in https://github.com/JuliusWelzel/mne-testing-data/commit/66678eb5993a8aa7b046dbfa154630c1df9847c7. Let me know if you are happy with this.

**Comment by agramfort** [comment]
it seems you can use a GZIPed of the .TSV see https://bids-specification.readthedocs.io/en/stable/modality-specific-files/physiological-and-other-continuous-recordings.html

**Comment by JuliusWelzel** [comment]
> it seems you can use a GZIPed

For physio yes, officially not for motion. But we will include this in the next release. Should I change it to GZIPed?

**Comment by agramfort** [comment]
if you think it will be added very shortly I would say yes.

**Comment by JuliusWelzel** [comment]
Has this been merged so I can start adding motion data to MNE and MNE-BIDS?

**Comment by agramfort** [comment]
I would say so !

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-testing-data/releases/tag/0.153

**Pull request merged**
