### PR TITLE
Add nirscout recording with nirstar 15.3

### PR DESCRIPTION
**Pull request by rob-luke**
Add nirx test recording for latest software version.

### Data collection process.

* Using NIRSite 2020.07 create the following montage

NIRSite_2020_07_Source_coordinates

NIRSite_2020_07_Detector_coordinates

* Which results in these distances (to be used in MNE tests

NIRSite_2020_07_Channel_Distances

* This is exported to NIRSTar 15.3 which results in the following configuration

NIRStar_15_3_PredefinedMontage

NIRStar_15_3_ChannelSetup

NIRStar_15_3_TopoLayout

NIRStar_15_3_ChannelMasking

* A measurement was then taken that looks like

NIRStar_15_3_Calibration

NIRStar_15_3_Recording

### CODE REVIEW

**Comment by rob-luke** [comment]
@larsoner and @agramfort let me know if this is ok and I can cut the new release.

I have already written tests in MNE and will PR that branch once this is merged. See https://github.com/rob-luke/mne-python/tree/nirstart153

**Comment by rob-luke** [comment]
File size is 420 KB

**Comment by agramfort** [comment]
ok for me !

thx

>

**Comment by rob-luke** [comment]
Ok I will merge and cut now. Thanks

**Pull request merged**
