### PR TITLE
[ENH] Add FIL post-HFC examples for comparative testing.

### PR DESCRIPTION
**Pull request by georgeoneill**
In preperation for [adding HFC to MNE](https://github.com/mne-tools/mne-python/pull/11536), added processed datasets using SPM/FieldTrip to facilitate unit tests.

### CODE REVIEW

**Comment by larsoner** [comment]
How about 0.1 sec? Or even just 10 or so samples? It should be enough assuming the projection is geometry-driven (rather than data-driven, which I think it is?)

**Comment by georgeoneill** [comment]
Yes, it is geometric, so should be entirely determinisitc. I'll drop it down to 300 samples for now. :)

**Comment by larsoner** [comment]
`BIN +162 KB` Beautiful!

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-testing-data/releases/tag/0.145

**Pull request merged**
