### PR TITLE
[MRG] fix bv files in montage test

### PR DESCRIPTION
**Pull request by sappelhoff**
first step in fixing:

- https://github.com/mne-tools/mne-python/issues/11113

- replaced existing binary data in .eeg with some that I got from a similar pilot recording from my institute
- updated the corresponding fif file
- I also noticed two issues in the vhdr file that are fixed here
- Not sure why the fif file is now 80 bytes larger. Perhaps we started writing more metadata to it via mne-python since the last time I touched this file.

tests in mne-python still pass after this (`pytest mne/channels/tests/test_montage.py`), and the data in BrainVision and FIF are identical (up to 1e-7 absolute tolerance).

### CODE REVIEW

**Comment by sappelhoff** [comment]
cc @larsoner @hoechenberger

**Comment by larsoner** [comment]
> Not sure why the fif file is now 80 bytes larger. Perhaps we started writing more metadata to it via mne-python since the last time I touched this file.


If you want to investigate, `mne compare_fiff <old> <new>` should be informative

**Comment by sappelhoff** [comment]
cool, thanks for the hint!

image

**Comment by agramfort** [comment]
good to go from your end @sappelhoff ? if so I'll merge and cut a release

**Comment by sappelhoff** [comment]
good to go from my side :+1:

**Comment by agramfort** [comment]
done

https://github.com/mne-tools/mne-testing-data/releases/tag/0.139

**Comment by sappelhoff** [comment]
thank you :-)

**Pull request merged**
