### PR TITLE
Add EDF file with UTF8 annotations

### PR DESCRIPTION
**Pull request by cbrnr**
Required to test https://github.com/mne-tools/mne-python/pull/10963.

### CODE REVIEW

**Comment by cbrnr** [comment]
I don't want to clone the whole repo locally (I'm on a slow connection RN), so can someone please bump the version?

**Comment by larsoner** [comment]
> I don't want to clone the whole repo locally (I'm on a slow connection RN), so can someone please bump the version?

For future ref you can get to it by clicking through

https://github.com/cbrnr/mne-testing-data
https://github.com/cbrnr/mne-testing-data/tree/edf-utf8-annotations
https://github.com/cbrnr/mne-testing-data/blob/edf-utf8-annotations/version.txt
https://github.com/cbrnr/mne-testing-data/edit/edf-utf8-annotations/version.txt

**Comment by larsoner** [comment]
(this is what I just did)

**Comment by cbrnr** [comment]
Thanks @larsoner! I should have tried that, because that's how I added the file and created the PR.

**Pull request merged**
