### PR TITLE
Adding file to test reading hdf5 formatted data

### PR DESCRIPTION
**Pull request by smgutstein**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
This is 6.22 MB, any way you can make a smaller one?

Alternatively, can you (easily enough) construct an equivalent one on the fly with `h5py` in the tests, knowing the fields and values?

**Comment by smgutstein** [comment]
No problem. Would 2-3 MB be reasonable?

**Comment by agramfort** [comment]
the smaller the better

**Comment by agramfort** [comment]
this one is 2.35MB

I am merging it.

thx @smgutstein 

I'll give you instructions to update your PR to use this new testing data

**Comment by agramfort** [comment]
FYI I just forced push a squashed version as github did a merge commit

**Comment by agramfort** [comment]
you have now a new release. https://github.com/mne-tools/mne-testing-data/releases/tag/0.38

you can update the testing dataset to version 0.38 and change the hash 

let me know if you need help

**Comment by smgutstein** [comment]
I just tried testing again, but the upstream test still isn't finding
test_raw_hdf5.set:

ERROR: Test importing EEGLAB .set files.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\conda\envs\test\lib\site-packages\nose\case.py", line 197, in
runTest
    self.test(*self.arg)
  File "C:\conda\envs\test\lib\site-packages\numpy\testing\decorators.py",
line 147, in skipper_func
    return f(*args, **kwargs)
  File "C:\conda\envs\test\lib\site-packages\numpy\testing\decorators.py",
line 147, in skipper_func
    return f(*args, **kwargs)
  File "C:\projects\mne-python\mne\io\eeglab\tests\test_eeglab.py", line
77, in test_io_set
    eeg = _get_eeg_data(raw_fname_hdffile)
  File "C:\projects\mne-python\mne\io\eeglab\eeglab.py", line 447, in
_get_eeg_data
    eeg_dict = hdf_2_dict(f, f['EEG'], prefix=None)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
(C:\Minonda\conda-bld\h5py_1490028453082\work\h5py\_objects.c:2867)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
(C:\Minonda\conda-bld\h5py_1490028453082\work\h5py\_objects.c:2825)
  File "C:\conda\envs\test\lib\site-packages\h5py\_hl\group.py", line 169,
in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
(C:\Minonda\conda-bld\h5py_1490028453082\work\h5py\_objects.c:2867)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
(C:\Minonda\conda-bld\h5py_1490028453082\work\h5py\_objects.c:2825)
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
(C:\Minonda\conda-bld\h5py_1490028453082\work\h5py\h5o.c:3628)
KeyError: "Unable to open object (Object 'eeg' doesn't exist)"

I don't understand why, since the file appears to be where it is supposed
to be:
raw_fname_hdffile = op.join(base_dir, 'test_raw_hdf5.set')

Is there something I should do? It still tests fine on my local machine.

Thanks

On Tue, Aug 1, 2017 at 2:33 AM, Alexandre Gramfort <notifications@github.com

**Comment by Eric89GXL** [comment]
I assume you're talking about the changes over in https://github.com/mne-tools/mne-python/pull/4056/files#diff-17ae6259472b040a1441c4d11af2bc06?

If so, as [Alex suggested](https://github.com/mne-tools/mne-testing-data/pull/26#issuecomment-319281191) you need to update `mne/datasets/utils.py` to change the `testing` tag to `0.38`, and then also update the associated hash (which you can do after changing the tag to 0.38 by doing `mne.datasets.testing.data_path(force_update=True, verbose=True)` which will fail but give you the new hash)

**Comment by Eric89GXL** [comment]
I have now tried to make this more explicit in the README:

https://github.com/mne-tools/mne-testing-data/blob/master/README.md#add-or-change-files-in-the-repo-for-use-with-mne

**Comment by smgutstein** [comment]
Hi,

This is a little embarrassing, but I really don't understand exactly what
it is you're asking me to do. My main questions are:

1. In  mne/datasets/utils.py, I can find line 231: "releases =
dict(testing='0.36', misc='0.3')". Am I correct in assuming that here (and
only here) is where I should change "testing='0.36' " to "testing='0.38' "?

2. In line 281, there is a dictionary called "hashes". One of its keys is
"testing='03e84fe9a50dfeb04ab5f138ceed441d' ". Am I correct in assuming
that "03e84..." should be replaced with the hash produced by running
mne.datasets.testing.data_path(force_update=True, verbose=True)?

3. I tried running mne.datasets.testing.data_path(force_update=True,
verbose=True) and got the following Runtime error:

"Hash mismatch for downloaded file
/home/smgutstein/mne_data/mne-testing-data-0.38.tar.gz.part, expected
03e84fe9a50dfeb04ab5f138ceed441d but got d53058bb4068c96e7aae2c4f10f1bd47"

However, when I do a git log, the only two hashes I see subsequent to
adding test_raw_hdf5.set are:

---------------------------------------------------------------------------
commit 50024f74551a50ac23cef6ff2d18bb211f472b1d
Author: Alexandre Gramfort <alexandre.gramfort@m4x.org>
Date:   Tue Aug 1 08:31:52 2017 +0200

    Update version.

commit 8f57bf1a1276285e3502b73394f07f26d74a85bd
Author: Moonpie McGee <s.m.gutstein@gmail.com>
Date:   Sun Jul 30 02:35:37 2017 -0400
---------------------------------------------------------------------------

So, will the d53058 hash contain test_raw_hdf5.set?

4. Where is version.txt? I can't find it in mne-python

Thanks, I realize my inexperience is showing here and hope I'm not missing
anything too utterly obvious.....

**Comment by Eric89GXL** [comment]
> Am I correct in assuming that here (and
only here) is where I should change "testing='0.36' " to "testing='0.38' "?

Yep

> Am I correct in assuming
that "03e84..." should be replaced with the hash produced by running
mne.datasets.testing.data_path(force_update=True, verbose=True)?

Yep

> 03e84fe9a50dfeb04ab5f138ceed441d but got d53058bb4068c96e7aae2c4f10f1bd47

So the `03...` hash you can recognize from point (2) above, i.e. line 281. Change it to the `d5...` hash and you should be good to go.

These hashes are the MD5sum hashes of the tar downloads and are only indirectly related to the GitHub commit hashes.

**Pull request merged**
