### PR TITLE
MRG data for testing EEGLAB reader

### PR DESCRIPTION
**Pull request by jasmainak**
cf https://github.com/mne-tools/mne-python/pull/2676

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Let me know when it's ready for merge

**Comment by Eric89GXL** [comment]
(you won't be able to test your code against it on Travis until it's merged, but you can copy the files manually to your own local copy for testing)

**Comment by jasmainak** [comment]
yeah, I might add a few more files for some corner cases.

**Comment by agramfort** [comment]
merge when you're happy

**Comment by jasmainak** [comment]
@agramfort ready to merge.

**Pull request merged**
