### PR TITLE
WIP: Artemis123 datasets for IO testing

### PR DESCRIPTION
**Pull request by bloyl**
testing data for artemis123 io.
related to PR WIP: IO support for artemis123 support #3754

### CODE REVIEW

**Comment by agramfort** [comment]
thx @bloyl 

how big is the file?

**Comment by bloyl** [comment]
These are relatively small
11M	Artemis_Data_2016-11-03-15h-58m_test.bin
8.0K	Artemis_Data_2016-11-03-15h-58m_test.txt

most likely I'll want to add one that is a bit larger in the 400M range at some point. Do you think that would be an problem?

**Comment by agramfort** [comment]
11M is good

why do you need a bigger file just to test IO?

**Comment by bloyl** [comment]
That file wouldn't be to test IO but to test HPC localization. The data is acquired at 5 kHz so it accumulates quickly.

I can also foresee adding an evoked dataset for regression tests of other functionality that might depend on the coil and/or sensor geometry, things like forward modeling etc.

Neither of those things are imminent so we could deal with those later. Alternatively we could hold off on merging the PR until there is a minimum of dataset that fulfills all of these needs.

At this point I'm really just trying to get some basic code review on the IO code.

**Comment by agramfort** [comment]
I am fine merging this PR and to keep the rest for later.

ok for you?

**Comment by bloyl** [comment]
+1

**Comment by Eric89GXL** [comment]
11mb with cHPI sounds good to me

**Comment by agramfort** [comment]
@Eric89GXL I'll let you merge and make the release.

bed time here :)

**Comment by bloyl** [comment]
This 11mb does not have chpi. The smallest I have with chpi right now is
approx 400mb

**Comment by Eric89GXL** [comment]
Oh okay. Let's find a smaller one for that later

**Comment by Eric89GXL** [comment]
Okay @bloyl I made release 0.27, update your MNE-Python PR [here] (https://github.com/mne-tools/mne-python/blob/master/mne/datasets/utils.py#L228) (version number and hash for `testing`) and the CIs should respond properly. And don't forget to remove and squash out your file there.

**Pull request merged**
