### PR TITLE
Add EGI MFF with PNS data

### PR DESCRIPTION
**Pull request by fraimondo**

### CODE REVIEW

**Comment by larsoner** [comment]
Why is there a `.bak` file in there?

What is the total added size?

**Comment by fraimondo** [comment]
The .bak file is part of the EGI format. I did not touch that file, just made a very short recording and copied the file there.

Here's a summary of the file sizes. I'm just adding 10.7 M.

mia ➜  EGI git:(master) du -sh ./*
 11M	./test_egi.mff
7.0M	./test_egi_pns.mat
3.7M	./test_egi_pns.mff

**Comment by fraimondo** [comment]
with file I mean the MFF file/package.

**Comment by larsoner** [comment]
Makes sense. Is this the smallest file you can produce / find that allows you to properly test?

**Comment by fraimondo** [comment]
It is 257 electrodes + 7 PSN channels. I've started recording and touched the contacts in this order:
```Python
['Resp. Temperature', 'Resp. Pressure', 'ECG', 'Body Position',
 'Resp. Effort Chest', 'Resp. Effort Abdomen', 'EMG-Leg']
``` 

If you visually inspect the file, you should see flat noise and some peaks in that order, although the temp and position have some internal interpretation so there are no peaks.

This recording last a few seconds and it takes 3.7 M. The MAT file is to check that the data is the same with an official EGI export. Unfortunately, the MAT files is heavier than the MFF and makes it 7.0M.

It is less than an internal block of samples, so the `test_egi.mff` file is still needed to check how everything works when there are several blocks and also trigger channels.

**Comment by larsoner** [comment]
Okay I cut a new release https://github.com/mne-tools/mne-testing-data/releases/tag/0.40

**Pull request merged**
