### PR TITLE
Add valid SNIRF file

### PR DESCRIPTION
**Pull request by rob-luke**
We already have several SNIRF files as provided by different vendors. However, none of these are actually compliant with the SNIRF specification, as tested using the official snirf validator (https://github.com/BUNPC/pysnirf2). This PR adds a valid SNIRF file (as generated by MNE-NIRS) that passes the latest version of the validator. We want to ensure that we can actually read valid SNIRF files!

This file was created from a nirx measurement using the following script.
```python
import mne
import mne_nirs
raw = mne.io.read_raw_nirx("../../../NIRx/nirscout/nirx_15_3_recording/")
  Loading ../../../NIRx/nirscout/nirx_15_3_recording/
mne_nirs.io.write_raw_snirf(raw, "20220217_nirx_15_3_recording.snirf")

# Validate that the file is SNIRF compliant
import pysnirf2
pysnirf2.validateSnirf("20220217_nirx_15_3_recording.snirf")
Out[7]: <pysnirf2.pysnirf2.ValidationResult object at 0x10eae3d90> is_valid True
```

The file size is 135 KB.

### CODE REVIEW

**Comment by rob-luke** [comment]
@larsoner could you please review

**Comment by sstucker** [comment]
What was the issue the validator raised (I am being nosy as the validator is still a WIP)

**Comment by rob-luke** [comment]
Sorry @sstucker, my description wasnt clear.
This repository stores our test data. We have collected test data (small files of just a few seconds with known parameters) from many manufacturers and software. Many of these collected files are not SNIRF compliant. And your validator correctly marks them as not SNIRF compliant. So no problems. But I wanted to include a test file that was valid, and its handy to ensure that we are backwards compliant with MNE-NIRS too

But here is some output...

```python
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pysnirf2

In [2]: r = pysnirf2.validateSnirf("/Users/rluke/mne_data/MNE-testing-data/SNIRF/NIRx/NIRSport2/2021.9/2021-10-01_002.snirf")
   ...:

In [3]: r
Out[3]: <pysnirf2.pysnirf2.ValidationResult object at 0x1057ff820> is_valid False

In [4]: r.display()
<pysnirf2.pysnirf2.ValidationResult object at 0x1057ff820>
//formatVersion                                        FATAL   INVALID_DATASET_SHAPE
/nirs/metaDataTags/SubjectID                           FATAL   INVALID_DATASET_SHAPE
/nirs/metaDataTags/MeasurementDate                     FATAL   INVALID_DATASET_SHAPE
/nirs/metaDataTags/MeasurementTime                     FATAL   INVALID_DATASET_SHAPE
/nirs/metaDataTags/LengthUnit                          FATAL   INVALID_DATASET_SHAPE
/nirs/metaDataTags/TimeUnit                            FATAL   INVALID_DATASET_SHAPE
/nirs/metaDataTags/FrequencyUnit                       FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList1/sourceIndex               FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList1/detectorIndex             FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList1/wavelengthIndex           FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList1/dataType                  FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList1/dataTypeIndex             FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList2/sourceIndex               FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList2/detectorIndex             FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList2/wavelengthIndex           FATAL   INVALID_DATASET_SHAPE
/nirs/data1/measurementList2/dataType                  FATAL   INVALID_DATASET_SHAPE
...
...
...
/nirs/stim1/name                                       FATAL   INVALID_DATASET_SHAPE
/nirs/stim2/name                                       FATAL   INVALID_DATASET_SHAPE
/nirs/probe/landmarkLabels                             WARNING FIXED_LENGTH_STRING

Found 52 OK      (hidden)
Found 368 INFO    (hidden)
Found 1 WARNING
Found 229 FATAL

File is INVALID

```

**Comment by sstucker** [comment]
Got it. I was curious what the issues with the files are and checking to make sure nothing suspicious is going on with the validator. This makes sense to me: variables saved with array dataspaces. We will fix this formatting issue in the Homer release soon

**Comment by larsoner** [comment]
Can we just update the existing incorrect SNIRF files to be correct instead?

**Comment by rob-luke** [comment]
> Can we just update the existing incorrect SNIRF files to be correct instead?

The existing files are exported directly from vendor hardware/software. So we should keep them as is to ensure we can say "we support reading nirx/kernel devices".

**Comment by rob-luke** [comment]
Having said that, in the future i hope all vendors export data in the correct snirf format and then we can drop support for these files that aren't compliant

**Comment by larsoner** [comment]
@rob-luke do you want to make a quick PR for the `git mv` or `rm` of the files from https://github.com/mne-tools/mne-testing-data/commit/94ac227f2cfdb88dd772596d517afd272931e117 ? I'm happy with either solution. I guess `rm` is actually a bit better because it decreases our testing dataset size.

I'll do `rm` and cut a release in the next half hour or so unless you get to it, or suggest you prefer just to `git mv`

**Comment by rob-luke** [comment]
Thanks

**Pull request merged**
