### PR TITLE
Kernel Flow50 haemoglobin SNIRF

### PR DESCRIPTION
**Pull request by rob-luke**
Adds a SNIRF file that contains measurements of haemoglobin data (the other testing data files are raw voltage measurements). This test data will then be used in the https://github.com/mne-tools/mne-python/pull/9929 PR

#### Info from vendor

The vendor supplied the file with the following details. I will update the MNE-Python PR to test these values

- Both files have 1.574 s of data
- there are 12 sources and 72 detectors (12 modules), on the forehead
- only channels up to a SDS of 30mm are in the recording (180 channels, 8 of them populated with NaN because we rejected their data)
- sampling rate for each channel is ~8.256Hz
- there are two triggers in the data "start_trial" (at time 0.037 s) and "start_ITI" (at time 0.875 s) (note that the exact names of the columns and events are different in the SNIRF file, where we use PascalCase for compatibility with Homer3)

|  |  timestamp | event | duration | experiment_type | block | block_type | trial | trial_type |
| ---  | --- | --- | --- | --- | --- | --- | --- | --- |
| 0 | 0.036939 | start_trial| 0.790963| finger_tapping| 1.0 | right | 1.0 | pinky | 
| 1 | 0.874633	| start_ITI | 0.861641 | finger_tapping | 1.0 | right | NaN | nan |

### CODE REVIEW

**Comment by rob-luke** [comment]
@larsoner @agramfort can you please review, this is ready on my end

**Comment by rob-luke** [comment]
Thanks @larsoner
Please be quicker next time!

**Comment by larsoner** [comment]
To make it up to you, here's the release MD5 I got locally :)

88c04e31fd496f394fa96fe7cdd70217

**Comment by rob-luke** [comment]
haha thanks!

**Pull request merged**
