### PR TITLE
Add new-style EEGLAB test file (no EEG struct)

### PR DESCRIPTION
**Pull request by cbrnr**
Required to test https://github.com/mne-tools/mne-python/pull/8874.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@cbrnr The file seems to be empty?

Also, you need to update a few more places :) https://github.com/mne-tools/mne-testing-data#mne-testing-data

**Comment by larsoner** [comment]
Why not read an existing file and write to `tmpdir` with the fields at the root instead? That's the pattern I've been using recently for things that require small tweaks like this

Also the file here shows as zero bytes

**Comment by hoechenberger** [comment]
> Why not read an existing file and write to `tmpdir` with the fields at the root instead?

This was my original proposal but since this is going to be the EEGLAB format of all future versions (well… until something newer comes along), it does make sense to have a proper testing file available

**Comment by cbrnr** [comment]
I wanted to avoid cloning the repo because it usually takes ages, so I tried doing everything on GitHub. Obviously, that didn't work. Can either one of you add this file? If I have to do it it might take a while...

Yes, I usually prefer to modify things on the fly as well, but in this case I'd rather have a real and tested file.

[test_raw_2021.zip](https://github.com/mne-tools/mne-testing-data/files/5991502/test_raw_2021.zip)

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-testing-data/releases/tag/0.116 with hash ee36633fa9872aa434cc91f836beaa45

**Pull request closed without merging**
