### PR TITLE
Add eyelink file with HREF data type

### PR DESCRIPTION
**Pull request by scott-huberty**
Added an eyelink file with HREF data, so that we can test our code that converts the unit to radians

### CODE REVIEW

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-testing-data/releases/tag/0.144

**Comment by scott-huberty** [comment]
Thanks @larsoner - On what file in `mne-testing-data` should I check the md5 hash for? I'm not sure how to find, but i'll need to update the hash in `mne.datasets/conf.py`

**Comment by scott-huberty** [comment]
ah. Think I got it. I'm getting `9ef1bc86f1cdebf0e97603206a4f7b16` for the `mne-testing-data-0.144.zip`

**Comment by larsoner** [comment]
You want to use the .tar.gz

**Comment by scott-huberty** [comment]
Thank you!!

**Pull request merged**
