### PR TITLE
Add Data for artemis cHPI and Head loc testing

### PR DESCRIPTION
**Pull request by bloyl**
Data for https://github.com/mne-tools/mne-python/pull/4069
17M	 ----- ARTEMIS123/Artemis_Data_2017-04-04-15h-44m-22s_Motion_Translation-z.bin
8.0K -----	ARTEMIS123/Artemis_Data_2017-04-04-15h-44m-22s_Motion_Translation-z.txt
4.0K	 ----- ARTEMIS123/Artemis_Data_2017-04-04-15h-44m-22s_Motion_Translation-z_mc.pos
688K -----ARTEMIS123/Artemis_Data_2017-04-14-10h-38m-59s_Phantom_1k_HPI_1s.bin
8.0K	 ----- ARTEMIS123/Artemis_Data_2017-04-14-10h-38m-59s_Phantom_1k_HPI_1s.txt
24K -----	ARTEMIS123/Phantom_040417_dig.pos

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I assume 17 MB is as small as you can reasonably get the data and still have it be useful for testing? We want to keep the sizes here as small as possible. A 17 MB addition is non-trivial, but movecomp on other systems is important so it's worth it if it's the best you can do.

**Comment by bloyl** [comment]
So we can do cHPI fitting on anything we want for instance we could use 59s_Phantom_1k_HPI_1s.bin but there isn't any motion in that file so while you have a regression test there isn't much that might mess it up.

Why don't we keep the 17M file and I'll remove the old 11M test file

**Comment by Eric89GXL** [comment]
> Why don't we keep the 17M file and I'll remove the old 11M test file

Sure, if that works let's do it, assuming that the 17M file has a superset of what the 11M file has in terms of testing utility

**Comment by Eric89GXL** [comment]
Is this one ready, too?

**Comment by bloyl** [comment]
No. This one can't be merged untill the mne-python PR is merged as it will
break tests in master.

**Comment by Eric89GXL** [comment]
No it won't. Everything is tracked based on the release. So everything should work fine.

Good to go from your end?

**Comment by Eric89GXL** [comment]
(The `mne.datasets.utils.py` file has a `release` string that refers to the `mne-testing-data` release number. I'll cut a release as soon as this is merged, then in your PRs you tell them to use the new release number and new hash.)

**Comment by bloyl** [comment]
Ok. Yeah I'm good to go

**Comment by Eric89GXL** [comment]
Okay, you're good to go with release 0.32 in your PRs

**Pull request merged**
